(ns notes.paas
  (:require [clojure.java.io :as io]
            [clojure.data.json :as json]))

(def db-name "notes")

(defn localhost-uri [uid pwd]
  (str "mongodb://" uid ":" pwd "@localhost:27017/" db-name))

;-- dotCloud

(defn is-dotcloud? []
  (-> (io/file "/home/dotcloud/environment.json") .exists))

(defn dotcloud-uri [uid pwd]
  "Get dotCloud MongoDB URI. User 'uid' with password 'pwd' must exist
  for database 'notes'"
  (let [env-file "/home/dotcloud/environment.json"
        env (with-open [f (io/reader env-file)] (json/read f))
        mongo-host (get env "DOTCLOUD_MONGO_MONGODB_HOST")
        mongo-port (get env "DOTCLOUD_MONGO_MONGODB_PORT")]
    (str "mongodb://" uid ":" pwd "@" mongo-host ":" mongo-port "/" db-name)))

;-- OpenShift

(defn is-open-shift? []
  (System/getenv "OPENSHIFT_APP_UUID"))

(defn open-shift-uri [uid pwd]
  "Get OpenShift MongoDB URI. 'uid' and 'pwd' are ignored, instead uses
  OpenShift provided admin credentials for zero conf deployment."
  (str (System/getenv "OPENSHIFT_MONGODB_DB_URL") db-name))

(defn node-name []
  "For OpenShift we provide the gear name, for all other services return nil for now"
  (System/getenv "OPENSHIFT_GEAR_NAME"))

;-- Jelastic

(defn is-jelastic? []
  (= "jelastic" (str (System/getProperty "environment"))))

(defn jelastic-uri [uid pwd]
  "Get Jelastic MongoDB URI. 'uid' and 'pwd' are ignored, defined in
  jelastic environemnt configuration file."
  (str (System/getProperty "mongo_url")))

;-- Heroku

(defn is-heroku? []
  (System/getenv "MONGOHQ_URL"))                            ;TOOD: Move to userdefined env


(defn heroku-uri [uid pwd]
  "Get Heroku/MongoHQ MongoDB URI. 'uid' and 'pwd' are ignored, instead uses
  Heroku provided admin credentials for zero conf deployment. DB name is
  autogenerated"
  (System/getenv "MONGOHQ_URL"))

;-- CloudFoundry/IBM Bluemix

(defn is-cloudfoundry? []
  (System/getenv "VCAP_SERVICES"))

(defn cloudfoundry-uri [uid pwd]
  "Get CF/MongoDB URI. 'uid' and 'pwd' are ignored, instead uses
  CF provided admin credentials for zero conf deployment. DB name is
  autogenerated. Assuming mongodb-2.2 service at Bluemix for now"
  (let [conf (json/read-str (System/getenv "VCAP_SERVICES") :key-fn keyword)]
    (get-in conf [:mongodb-2.2 0 :credentials :url])))

(defn mongo-connection-uri [uid pwd]
  "Try to figure out runtime environment and resolve associated MongoDB
connection URI. Defaults to localhost and standard port"
  (cond (is-dotcloud?) (dotcloud-uri uid pwd)
        (is-open-shift?) (open-shift-uri uid pwd)
        (is-jelastic?) (jelastic-uri uid pwd)
        (is-heroku?) (heroku-uri uid pwd)
        (is-cloudfoundry?) (cloudfoundry-uri uid pwd)
        :else (localhost-uri uid pwd)))

;;Roadmap:
;AWS Beanstalk
;Azure